### ISSUE TITLE
Hip cooling fan not working 

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#10]
@ntsagarakis, @lurentz We were running a series of jump tests on the leg, but we noticed that the cooling fan on the hip actuator is not working. 
This issue should be resolved as soon as possible because this makes testing trajectories on the leg much harder since, each time we stop the leg, we have to wait for the hip actuator to cool down. Also, jumping motions tend to overheat the actuators easily, so proceeding this way is also not safe.

**Comment by Lurentz** [comment]
Ciao Guys,
i think we need to substitute fan and dcdc converter. (stefano cordasco\nikos)
Meanwhile im preparing a plastic support in order to have a proper fixation of the fan  against the hip structure.

**Comment by ntsagarakis** [comment]
Lorenzo, is the fan 48V fan? if yes it can be directly wired to the 48V power port of the motor driver bypassing he dc/dc.  Alternatively we can get a 48V fan and do this if the one that is there now is not 48V fan. The fan then will be always on

**Comment by Lurentz** [comment]
im not sure , i think is a 12v. since we dont have 48v fan so small.

**Comment by AndPatr** [comment]
@ADVRHumanoids/advr-facility the cooling fan died one again while I was testing some small jumps on the leg.
Maybe there is a loose connection which tends to break during jumping motions.

**Comment by TheCzar87** [comment]
The DC/DC are dying probably due the high backEMF generated from the jumps.
We need to figure it out another solution, probably a 48V fan supplied directly from the main bus is the  solution.
Do you agree @stecorda ?

**Comment by AndPatr** [comment]
The hip fan is currently attached directly to the 48V as is always on.

**Comment by AndPatr** [comment]
The hip fan in now attached to the 48V directly and hence stays always operational.
