### ISSUE TITLE
Install soft mat on the ground to protect the leg from unexpected ground collisions

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#11]
@ntsagarakis Right know, we have installed an "emergency" mat on the ground using tape (cannibalized from the lab) to avoid damage on the leg when touchdown does not happen as intended. This is crucial since the leg can occasionally land with the knee and this can cause damage to the parts and the actuators. Our emergency mat is barely holding, so ideally we would need another one, possibly more robust. Do we have one already in our facility which we can use or should we buy it?

**Comment by ntsagarakis** [comment]
I think we should have some rubber sheets in the workshop area to use. Also for now you can also consider inserting a screw in the linear guide sets a minimum in which the leg can drop at the hip level to just prevent the knee touching the ground if the leg falls.

**Comment by ntsagarakis** [comment]
Then you need to be sure that the hip plate edge operates above the height set by the screw that you insert in the linear guide
during the experiments to avoid impacts between the hip plate and that screw on the linear guide
