### ISSUE TITLE
We have lost the hip

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#13]
@ntsagarakis, @alaurenzi. @lucarossini-iit,
Yesterday evening we performed with @FrancescoRuscelli  a cyclic jump test on the leg in view of the  upcoming demos.
We first performed a test with fast filters enabled, but the leg registered a "torque reading out of range" and shut down. 
So we decided to test it with a medium filter, resulting in a successful sequence of 6 jumps.
At the moment of takeoff of the 7th jump, the leg hit the ground performing an unexpected movement.
We observe the following.
Hip temperature: 

![temp_hip](https://user-images.githubusercontent.com/90312267/196658106-93ca263d-880a-415f-b34b-b3fc11d9a36a.png)
Knee temperature:

![temp_knee](https://user-images.githubusercontent.com/90312267/196658211-933e8d62-353e-447f-a74d-9524a34ac663.png)

Hip current:

![hip_currents_p_notes](https://user-images.githubusercontent.com/90312267/196660549-26f4c0b1-3d23-4edd-962d-e4a84ba855a4.png)

This is the hip pos tracking:
![hip_pos_tracking](https://user-images.githubusercontent.com/90312267/196660730-e51f8801-4054-4559-9eb6-1e9e608a58a7.png)
As you see, we have performed 6 successful jumps and then, at the moment of takeoff of the 7th jump, the leg disconnected
(the position tracking during the flight phase is intentionally poor, since we lower joint impedance).

Unfortunately we don't have a video of the leg during the test, but our guess is that, due to the high temperatures at the hip, the hip joint disconnected/died. The impact with the ground made the rest.

Right after the crash, we tried again the test and the leg made a 1 successful jump, but during the transition to the 2nd jump it made clicking noises and jerky movements, so we killed the power supply with the emergency button (you can see the associated video [here](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EWTX3sO3Pd9KrYOz9ysK4jABQfVFgtmh_z4C76eGZVzVrg?e=ieop3L)).

This morning, I tried to control the leg to check its status and I see no current tracking in the hip:
 
![xbot2_gui_chart__20221019_104126_415](https://user-images.githubusercontent.com/90312267/196661888-b8651f88-0d64-42fe-a987-f9e52115ea85.png)

I am able to see the slaves via ecat master:
![terminal0](https://user-images.githubusercontent.com/90312267/196662005-5735140d-7df1-4be1-be5b-799e0cc8db28.png)

but I get this "NoNo@Motor etc.."message on the terminal (presumably for the hip motor):
![terminal2](https://user-images.githubusercontent.com/90312267/196662132-1e0d36a2-6c00-484d-add3-55a9fbd6a031.png)

The knee seems to be operating fine. The current tracking is good:
![xbot2_gui_chart__20221019_103950_255](https://user-images.githubusercontent.com/90312267/196662399-4b0d6dc7-369e-4fce-9232-a5a1ef624bdc.png)

We don't know if this could be due to disconnected cables inside the electronics, damages HD, both, or something else.

@ADVRHumanoids/advr-facility can you give us assistance?

**Comment by ntsagarakis** [comment]
The interpretation that the high temperature stopped the controller looks reasonable to me in the first incident.
Have you tried to manually backdrive the joints? how do the behave? do the generate any strange noise that looks different from before?

**Comment by AndPatr** [comment]
Yes, I tried. The knee has super high friction as always. The hip is relatively smooth.
I've never tried to backdrive the hip with the leg shutdown, so I don't have a reference for that, but I didn't feel any irregular noise or friction on it. There is a bit of resistance, but it is constant throughout the joint range

**Comment by ntsagarakis** [comment]
if this is looks normal then harmonic is fine probably and the problem may be the inverter/power stage of the motor driver. May be it was partially damaged  that allowed you to perform the 2 jumps but after it died.  These trials are stretching a lot the motor driver not only from the current demand but also due to spikes to the voltage bus due to very fast braking. They may be not completely absorbed by the dissipation circuit.

**Comment by ntsagarakis** [comment]
Please send an issue to the facility so they can check it as soon as we confirm the mechanically the joints are good, e.g. when you backdrive they look normal in terms of backdrivability and noise.

**Comment by AndPatr** [comment]
How should I send the issue to the facility? I have already tagged them in this issue.

**Comment by AndPatr** [comment]
@ntsagarakis, @ADVRHumanoids/advr-facility, @alaurenzi, @FrancescoRuscelli, @lucarossini-iit
We have lost the hip, again.
This morning I started a cyclic jumping stress test on the leg but, but right after the first jump the hip died.
From the ecat_master terminal we saw a torque_reading_out_of_range error, which is a problem we have been experiencing at impacts (issue which such be solvable with a new firmware flashing).
Here's a video of the test: [https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EaoWpBJ09TJIv0f4ZgQrEnoBoCak4YuRVj0j6fOGlWaf4Q?e=BFfJoB](test)
You see that the legs successfully performs the first jump. Then, after the impact, the hip is dead, but the control plugin is still on. So the leg makes a small jump just due to the tracking of the knee trajectory. As soon as I noticed this, I killed everything and, upon restarting, I saw that once again the hip was dead:

![image200](https://user-images.githubusercontent.com/90312267/199718825-4d4262ab-8d3d-4894-9fdf-0e67972223fc.png)

**Comment by ntsagarakis** [comment]
After restarting did you receive any error?  E.g. the torque_reading_out_of_range or any other error else from the hip joint?

I guess we need to open the hip motor controller it again tomorrow if it was not opened this afternoon already. May be something become again loose after the impact.

**Comment by AndPatr** [comment]
From what I remember, the output from the ecat_master terminal was clean.
This suggests, in my opinion, that the impact with the ground caused once again the detachment of one or more of the phase cables.

**Comment by stecorda** [comment]
Resoldering of the phase cable done properly once for all, tested on the bench. 
The leg is ready to be tested again, waiting for your feedback, (attention that the zero position could be upside down because of link mounting, please ask to Lorenzo to swap it if the zero position is not with the leg pointing to the floor).

**Comment by ntsagarakis** [comment]
So the same issue basically as before.
Thanks Stefano

**Comment by AndPatr** [comment]
The leg was mounted correctly and is now fully operational. 
Thanks @stecorda, @Lurentz.
I will move on with the tests.

**Comment by ntsagarakis** [comment]
perfect  thanks to all!
