### ISSUE TITLE
Not an issue: successful long cyclic jump test

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#17]
@ntsagarakis, @alaurenzi, @FrancescoRuscelli, @lucarossini-iit, @Lurentz, @stecorda, 
Friday I performed a long stress test on the leg. It jumped 40 times without issues of any kind. I forgot to log the currents during the test, so I made it again this morning.
In this case the leg jumped for 51 times without apparent issues (video of an extract of the test  [here](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EW-KAZ-gqG9IkIdtw7_wjisB9V66WFAdThzMXS0M5i8VGg?e=JCe1hv)).
These is some relevant data from the test:
Joint quadrature current:
![iq](https://user-images.githubusercontent.com/90312267/201623730-af20fd38-43ab-43fd-8fe8-7999045760db.png)

Position tracking:
![pos_tracking](https://user-images.githubusercontent.com/90312267/201623832-f55021c9-9654-4a97-b339-7a90d94f466b.png)

Joint efforts:
![meas_torques](https://user-images.githubusercontent.com/90312267/201624305-c396d028-aa79-4fd8-9bca-6843767f905b.png)

Quadrature current estimation(detail):
![i_q_model](https://user-images.githubusercontent.com/90312267/201624384-28dcfaab-1e70-4eec-9161-8c2b4d28c1de.png)

Measured mechanical power:
![meas_mech_power](https://user-images.githubusercontent.com/90312267/201624429-ae7b16e2-b75b-4746-a7f7-5802fd9e3508.png)
Zoom over a single jump:
![meas_mech_power_detail png](https://user-images.githubusercontent.com/90312267/201624444-90670593-18c4-4451-9b4e-87cad600c864.png)

Drivers temperatures:
![driver_temp](https://user-images.githubusercontent.com/90312267/201624484-be02df9c-0d21-4432-858f-156079eb2366.png)

I'll try to improve the aesthetics of the jump in the time I have before the demo, but as I discussed with Nikos Friday, this is probably the best we can get from the leg, given the current hardware and technology.

**Comment by ntsagarakis** [comment]
Very nice, we are getting there. Is this still with the phase calibration issue? I do not see it in the graphs of current and torque. They look consistent, no?
In any case we now reach 200Nm peaks in the knee that are just above the peak limits of the harmonic drive. So yes we should not expect much more with these drives and leg mechanics,apart from some further tuning as well playing with the lower leg structure and foot to make it lighter and reduce impacts. But is is already very good !!!!

**Comment by ntsagarakis** [comment]
We can now use it as testbed to tune the foot properties as well as perform the modulation of impedance an see if it can affect the performance of the jumping.

**Comment by AndPatr** [comment]
I guess that the phase miscalibration issue is not so big as we thought. The current and torque graphs look ok to me too (and also the position tracking during the takeoff phase).

**Comment by AndPatr** [comment]
@ntsagarakis in view of the upcoming test phase - after the demo - I would recommend to check the knee friction once and for all, to see if it is possible to restore the knee joint to a more or less low-friction condition.
