### ISSUE TITLE
Test rig not stiff enough

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#4]
After having conducted a series of tests, we noticed that the test rig tends to vibrate/oscillate too easily.
 
This [link](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/Eai7hbBc68ZLkt7mgtqtsowBnawXckPZ9Z7KAAQlBfUZPw?e=aZtAM0) holds a representative video of the test rig oscillating while testing a trajectory on the leg.
Even if the trajectory is relatively aggressive, it is still far from the velocity limits of the actuators (see
[q_dot.pdf](https://github.com/ADVRHumanoids/awesome_leg/files/7960493/q_dot.pdf).
So, as of now, the current state of the test rig prevents us from doing more aggressive tests on the leg.
Furthermore, the vibrations can impact the quality of the results also in case of less aggressive trajectories.

**Comment by ntsagarakis** [comment]
ok, we need a different much more heavier bench or find a way to fix the bench to the ground.   I will check with Lorenzo if we can identify a heavy duty bench that can be more stable.
Can you share also any date concerning the torques or currents during this trial, how far we are from the limits

**Comment by AndPatr** [comment]
Actually, as of now I can only show you the ideal torques, etc.. as outputted by the trajectory generation script.
Here we have:
- [link_side_efforts.pdf](https://github.com/ADVRHumanoids/awesome_leg/files/7961750/link_side_efforts.pdf)
- [i_q.pdf](https://github.com/ADVRHumanoids/awesome_leg/files/7961756/i_q.pdf) 
For what concerns the currents, consider these values are actually underestimated because they do not account for some unmodeled effects (mainly static and dynamic frictional torques). A more general model of the currents which also accounts for friction is almost ready and shows promising results. Once ready, this model can and will be integrated into the optimization process (we can discuss the details next week, if you want).
I did not log any data from the robot during the test because the main focus was to show the vibration of the test rig.
If you want, I can run again the test on Monday and log all the necessary data during the test.

**Comment by AndPatr** [comment]
@ntsagarakis We have conducted a new test on the leg to verify the vibrations on the modified test bench.
The results can be seen in this [video](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EeWinZG-0FpLqt4aVdNMc7gB6uJsH7ZFGwC_R6jiIH66wA?e=nCe4XM).
The table is much more stable; there are still some relatively small residual vibrations on the aluminum profiles.

While testing the trajectory we noticed the electronics pack behind the hip joint was rotating (see this [video](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EYUmoKpDtZpGsgYGWse23-8BsW9IIWfyPw7OGlNdf6tUuA?e=8H9sSx)).
Apparently, there is a broken 3D printed support part:
![broken3Dsupport](https://user-images.githubusercontent.com/90312267/153420764-ca403f95-c98e-4af9-b311-e51b5105c34f.jpg)

We are not really sure of the reason why the electronics rotates (probably some cables are pulling it) and also of when and why the white support broke (the cause might the vibrations of the table during previous testing phases). 
Furthermore, we also noticed (it is visible in the picture) that the electronics plates are are only fixed using three of the available screw slots.

**Comment by ntsagarakis** [comment]
Yes it looks that the 3D printed part that is used to fix the motor driver to the actuator is either broker or became loose, may be due to the vibrations. The motion is produced indeed by the cables that pass through the joint and are connected to the link side, e.g. the torque sensor cable and the other cables

**Comment by ntsagarakis** [comment]
But but the trajectory looks very nice and clean, any logs for tracking errors, joint torques? is this under impedance control, what is the stiffness gain

**Comment by ntsagarakis** [comment]
thanks, how does the tracking error at the foot trajectory looks like?

**Comment by AndPatr** [comment]
As I said, unfortunately we didn't have the change to take log data from the leg during the test. As soon as the leg will be usable again we will run some tests and log all the necessary data.

**Comment by AndPatr** [comment]
@Lurentz, @ntsagarakis let us know as soon as the detached electronics will be fixed, so that we can move on with testing.
