### ISSUE TITLE
Gravity compensation tests

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#6]
This is just to have a trace of to the performed gravity compensation tests.
In particular, [this](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/EeJ6TIgldrhPskWD8A611yEBT3EUzkdF9pvm8tnLk34Zfw?e=6T7ZBK) video contains an example test.
A simple parameter identification procedure was carried out to calibrate some of the relevant inertial parameters of the leg (mass and CoM position along the links).
The gravity compensation works fine for most of the leg positions. 
We noticed some drift at some particular poses (clearly visible at the end of the video), which might be due to torque sensors hysteresis.

**Comment by AndPatr** [comment]
Yes, the test was performed with 0 stiffness and damping. A small damping would for sure mask the drift on the hip.
Original inertial params:
- HIP -> mass: 2.7264471e+00 ; x_CoM = 2.5796600e-05; y_CoM =1.8102660e-01 ; z_CoM = 8.5669756e-02; moments of inertia not calibrated
- KNEE -> mass: = 1.1927236e+00; x_CoM = 1.9572282e-01; y_CoM = -1.4549221e-02; z_CoM = -2.0785942e-02; moments of inertia not calibrated

Calibrated inertial params:
- HIP -> mass: 2.72644710e+00 ; x_CoM = 2.02539722e-03; y_CoM =2.36232975e-01 ; z_CoM = 8.56697560e-02; moments of inertia not calibrated
- KNEE -> mass: = 1.23787877e+00; x_CoM = 1.52366156e-01; y_CoM = -3.92736885e-04; z_CoM = -2.00277153e-02; moments of inertia not calibrated

**Comment by ntsagarakis** [comment]
Thanks. there some differences that I would not expect to be so large, e.g. the x_com of knee, 0.04 difference looks large unless we missed something in the CAD-generated model.

**Comment by AndPatr** [comment]
Well, actually I'd say you shouldn't consider these values to be physically consistent with the actual robot. They are only a combination which fits good the static testes we made.
In total, the dynamics has 10 inertial parameters per joint (mass, mass * x_com, mass * y_com, mass *  z_com, ixx, ixy, ixz, iyy, iyz, izz), so the total regressor has dimension (n_samples * n_joints) x (10 * n_joints).
It turns out that, with the available static measurements, the total regressor has a rank of 4, associated with columns 1, 2, 11, 12 of the regressor.
This means that we can only get  the products (mass * x_com, mass * y_com) for both links using static poses.

**Comment by alaurenzi** [comment]
After discussing with Nikos, let's improve this task by
 - [ ] producing a nice picture of the static poses 
 - [ ] adding new poses to address the drifting "issue" in the upper part of the workspace
 - [ ] re-calibrating the parameters

**Comment by AndPatr** [comment]
@Nikos, just to address the first point, here it is a collage of the 13 different poses used to calibrate the inertial parameters:

![pose_collage](https://user-images.githubusercontent.com/90312267/154811501-a72b0512-6b1e-4b42-8fbb-155d64164bfa.jpg)

As you see, there were actually some poses with different elbow convexity and also a couple near the top of the range.
